// =====================================================================
// Local Products Data
// Fallback data source used when Supabase table is empty or unavailable.
// Images are served from the public/ directory.
// =====================================================================

import type { Product } from "@/lib/types";
import { IPHONE_PRODUCT } from "@/lib/iphone-15-pro-max-data";

/**
 * Maps product slugs to their actual folder names on disk.
 * Folder names contain spaces and mixed case while slugs are kebab-case.
 */
export const SLUG_TO_FOLDER: Record<string, string> = {
  "anti-snoring-chin-strap": "Anti-snoring chin strap",
  "blackhead-remover-vacuum-tool": "Blackhead remover vacuum tool",
  "eye-massager-sleep-mask": "Eye massager sleep mask",
  "foot-massage-roller-spiked": "Foot massage roller",
  "kitchen-sink-drain-hair-catcher": "Kitchen sink drain hair catcher",
  "magnetic-usb-cable-3-in-1": "Magnetic USB cable",
  "menstrual-heating-pad-usb": "Menstrual heating pad (USB)",
  "posture-corrector-belt": "Posture corrector belt",
  "silicone-oil-splatter-guard": "Silicone oil splatter guard",
  "waterproof-phone-pouch": "Waterproof Phone Pouch",
  "waterproof-shoe-covers": "Waterproof shoe covers",
  "samsung-galaxy-s23-ultra":
    "Part-2/Samsung Galaxy S23 Ultra Dual SIM Smartphone 12GB RAM 512GB Storage - Internationa Version",
  "iphone-15-pro-max-512gb":
    "Part-2/iPhone-15-Pro-Max-512GB-Smart-Phone-Mega-Deal-Offer",
  "messi-argentina-2026-jersey":
    "Part-2/Messi 10 Jersy Argentina world cup 2026",
};

/**
 * Maps product slugs to their image filenames (in display order).
 * First image is used as the primary / thumbnail.
 */
export const SLUG_TO_IMAGES: Record<string, string[]> = {
  "anti-snoring-chin-strap": [
    "713s6nBocOL._AC_SX679_.jpg",
    "71J7WCcLYrL._AC_SX679_.jpg",
    "61scJnV6E-L._AC_SX679_.jpg",
    "61XQvLpMfpL._AC_SX679_.jpg",
    "71mznW03Z6L._AC_SX679_.jpg",
    "71Uhi+rYZNL._AC_SX679_.jpg",
    "71YcArmgXUL._AC_SX679_.jpg",
    "videoframe_6701.png",
  ],
  "blackhead-remover-vacuum-tool": [
    "71UD1hZ6dEL._SL1500_.jpg",
    "51GX34Y6rBL._SX679_.jpg",
    "61FqTSjngEL._SL1500_.jpg",
    "61g7pE6PkOL._SL1500_.jpg",
    "61uM4gsQqML._SL1500_.jpg",
    "71QZVdPJ+yL._SL1500_.jpg",
    "717f90hhyfL._SL1500_.jpg",
  ],
  "eye-massager-sleep-mask": [
    "71buUGZPyGL._SL1500_.jpg",
    "715zY+gU7mL._SL1500_.jpg",
    "71GluIfTU6L._SL1500_.jpg",
    "71hzVF4EzGL._SL1500_.jpg",
    "71phq6UFSCL._SL1500_.jpg",
    "71t+c1kTBZL._SL1500_.jpg",
    "71XwXWvRypL._SL1500_.jpg",
    "81P7fDd4NxL._SL1500_.jpg",
  ],
  "foot-massage-roller-spiked": [
    "71C6y5PaQcL._SL1024_.jpg",
    "51DCC5qK4tL._SL1024_.jpg",
    "615MQIhrGHL._SL1024_.jpg",
    "61m8g2w4PvL._SL1024_.jpg",
    "61pCypom1FL._SL1024_.jpg",
    "61YrHxn0EML._SL1024_.jpg",
    "71nUphLK0oL._SL1024_.jpg",
  ],
  "kitchen-sink-drain-hair-catcher": [
    "81K4FfOClhL._SL1500_.jpg",
    "71CS2cGV1VL._SL1500_.jpg",
    "71OOgmOO6JL._SL1500_.jpg",
    "71OPTuvcqiL._SL1500_.jpg",
    "71QPoJSRjWL._SL1500_.jpg",
    "71UGLGSVhOL._SL1500_.jpg",
    "81dD5bagqGL._SL1500_.jpg",
    "81hk6x44btL._SL1500_.jpg",
    "81hW4gJrMiL._SL1500_.jpg",
  ],
  "magnetic-usb-cable-3-in-1": [
    "71K28ltxwML._SL1000_.jpg",
    "410L7EcP-QL._SL1500_.jpg",
    "41bYWVE1yLL._SL1000_.jpg",
    "41gwMn6x3aL._SL1500_.jpg",
    "41N6lAWqO0L._SL1500_.jpg",
    "51h2Uhwb5HL._SL1000_.jpg",
    "51TAiQT4T9L._SL1000_.jpg",
    "61LhXA9czEL._SL1000_.jpg",
  ],
  "menstrual-heating-pad-usb": [
    "4c1fa16d-e3f6-47e2-bc36-ddb1ad6125ab.avif",
    "567a9f6a-bb34-4b67-aaa0-f85b200bd71b.avif",
    "5fe65003-eb2e-4a69-8234-bed1d6b7a144.avif",
    "85bc355e-4994-11f0-b974-0a580a634d11.avif",
    "87d46062-f94f-4b3a-a326-20736ade87af.avif",
    "d479d970-a4ab-42a1-9c51-553ac1eefb91.avif",
    "ef012fbd-2b12-49ac-956b-fdde201e25f8.avif",
    "f27ed9de-6e7e-499b-aa2e-9b5f59889982.avif",
  ],
  "posture-corrector-belt": [
    "na-posture-corrector-magnetic-back-support-belt-shoulder-for-original-imah9chaghghhran.webp",
    "3ccd9b87-f8c5-4ecc-9f0e-a84b0dfff3ad.avif",
    "70837e82-fe26-4a7c-9743-8bb9ef3288cb.avif",
    "9c85db66-403b-47f7-b202-897b0a7e8658.avif",
    "afeafd61-1fb8-4745-867f-fb0d35fce8d6.avif",
    "BS63-1.webp",
    "c8ee076a-c889-4ba9-943b-02e203f4fbb1.avif",
  ],
  "silicone-oil-splatter-guard": [
    "81He5w+zsBL._AC_SX679_.jpg",
    "61BSr5zTGTL._AC_SX679_.jpg",
    "71CJiccJoOL._AC_SX679_.jpg",
    "71MnzyjNAZL._AC_SX679_.jpg",
    "71oRvYZ0wiL._AC_SX679_.jpg",
    "81gm-o-sL-L._AC_SX679_.jpg",
    "81vb7Kl7RZL._AC_SX679_.jpg",
  ],
  "waterproof-phone-pouch": [
    "81AKrS3Nf8L._AC_SL1500_.jpg",
    "71VJgi2YfvL._AC_SL1500_.jpg",
    "71xb2c4ykNL._AC_SL1500_.jpg",
    "71YyuYMG1HL._AC_SL1500_.jpg",
    "71zvzYEFsmL._AC_SL1500_.jpg",
    "81dGgyfFFeL._AC_SL1500_.jpg",
  ],
  "waterproof-shoe-covers": [
    "51iqWsou8wL.jpg",
    "41GVwI-6O9L._SY625_.jpg",
    "51nH48JYAEL.jpg",
    "51vmU9IGATL.jpg",
    "51ZZLnvjhvL.jpg",
    "616sjI+bQ6L.jpg",
    "videoframe_8838.png",
  ],
  "samsung-galaxy-s23-ultra": [
    "galaxy-s23-ultra-highlights-kv-1.jpg",
    "galaxy-s23-ultra-highlights-camera-1.jpg",
    "galaxy-s23-ultra-highlights-display-1.jpg",
    "Samsung Galaxy S23 Ultra Dual SIM Smartphone 12GB RAM 512GB Storage.jpg",
    "galaxy-s23-ultra-highlights-nightography-1.jpg",
    "galaxy-s23-ultra-highlights-spec-camera-1.jpg",
    "galaxy-s23-ultra-highlights-spen-more-1.jpg",
    "galaxy-s23-ultra-highlights-accessories-1.jpg",
    "galaxy-s23-ultra-highlights-one-ui-1.jpg",
    "galaxy-s23-ultra-highlights-wallet-1.jpg",
    "galaxy-s23-ultra-detail-press.jpg",
  ],
  "iphone-15-pro-max-512gb": [
    "Apple-iPhone-15-Pro-lineup-hero-230912_Full-Bleed-Image.jpg.xlarge_2x.jpg",
    "Apple-iPhone-15-Pro-lineup-design-230912_big.jpg.large_2x.jpg",
    "Apple-iPhone-15-Pro-lineup-camera-system-230912_big.jpg.large_2x.jpg",
    "iPhone-15-Pro-and-15-Pro-Max-1024x593.jpg",
    "4cc8b667f46992d4f4b9b3616298c244.webp",
    "9c676b63b6504d2bb7bf3b92d5fac4cd.webp",
    "51vq0INE3QL._AC_SL1500_.jpg",
    "61M+HNJhn6L._AC_SL1500_.jpg",
    "71nimWkOyjL._AC_SL1500_.jpg",
    "81y-tY6E9hL._AC_SL1500_.jpg",
    "81YSmKnlijL._AC_SL1500_.jpg",
    "718qqVErHNL._AC_SL1500_.jpg",
    "H6c195da845164cdaada13760b9748329C.avif",
    "iphone-15-pro-max-issues-scaled.webp",
    "pexels-photo-16004744.jpg",
    "storage_large_2x.webp",
  ],
  "messi-argentina-2026-jersey": [
    "Home/71DbIUtPvCL._AC_SX569_.jpg",
    "Home/71h9Len6zzL._AC_SX569_.jpg",
    "Home/71iX74mi2kL._AC_SX569_.jpg",
    "Home/71jKpmVS7VL._AC_SY606_.jpg",
    "Home/71lpsKaeG7L._AC_SX569_.jpg",
    "Home/71S5WdLyYpL._AC_SX569_.jpg",
    "Home/911VxI6UNHL._AC_SX569_.jpg",
  ],
};

export const LOCAL_PRODUCTS: Product[] = [
  {
    id: "prod-anti-snoring-chin-strap",
    name: "Anti-Snoring Chin Strap",
    slug: "anti-snoring-chin-strap",
    description:
      "Gently supports your jaw to keep airways open while you sleep — most users see reduced snoring from the very first night. Made from ultra-soft, breathable, skin-friendly stretch fabric with adjustable velcro straps.",
    price: 99,
    original_price: 198,
    discount_percentage: 50,
    category: "wellness",
    images: [],
    stock: 50,
    features: [
      "Soft & breathable stretch fabric — no irritation even after 8 hours",
      "Adjustable universal fit for most adult face shapes",
      "Slips on in 5 seconds — no batteries or complicated setup",
      "Lightweight (50 g) and travel-friendly",
      "7-day no-questions return policy",
    ],
    specifications: {
      Material: "Soft breathable stretch fabric",
      Size: "One size fits most adults (adjustable)",
      Weight: "50 g",
      Care: "Hand wash with mild soap, air dry",
      Colour: "Black / Dark grey",
    },
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "prod-blackhead-remover-vacuum-tool",
    name: "Blackhead Remover Vacuum Tool",
    slug: "blackhead-remover-vacuum-tool",
    description:
      "Safely clear blackheads and unclog pores with gentle suction. Features 5 interchangeable suction heads, USB rechargeable battery, and adjustable suction levels for all skin types.",
    price: 199,
    original_price: 355,
    discount_percentage: 44,
    category: "personal-care",
    images: [],
    stock: 40,
    features: [
      "5 interchangeable suction heads for different skin areas",
      "USB rechargeable — no batteries needed",
      "Adjustable suction levels for sensitive to deep cleansing",
      "LCD display shows suction level & battery",
      "Gentle on skin — reduces redness vs manual extraction",
    ],
    specifications: {
      Material: "ABS + Silicone",
      "Suction Heads": "5 interchangeable tips",
      Battery: "300 mAh (USB rechargeable)",
      "Charging Time": "1.5 hours",
      "Waterproof Rating": "IPX6",
    },
    is_active: true,
    created_at: "2025-01-02T00:00:00Z",
    updated_at: "2025-01-02T00:00:00Z",
  },
  {
    id: "prod-eye-massager-sleep-mask",
    name: "Eye Massager Sleep Mask",
    slug: "eye-massager-sleep-mask",
    description:
      "Relieve tired eyes with soothing heat and vibration massage. Features 5 massage modes, built-in Bluetooth music, foldable design, and rechargeable battery for relaxation anywhere.",
    price: 799,
    original_price: 1332,
    discount_percentage: 40,
    category: "wellness",
    images: [],
    stock: 25,
    features: [
      "5 massage modes (heat, vibration, compression, music sync)",
      "Built-in Bluetooth speaker — play calming music while you relax",
      "Foldable & lightweight design for travel",
      "USB rechargeable with 5+ hours of battery life",
      "Adjustable strap fits all head sizes",
    ],
    specifications: {
      Material: "Breathable memory foam + PU leather",
      Modes: "5 (Heat, Vibration, Compression, Music, Combo)",
      Battery: "500 mAh (USB-C rechargeable)",
      "Battery Life": "5+ hours",
      Weight: "210 g",
    },
    is_active: true,
    created_at: "2025-01-03T00:00:00Z",
    updated_at: "2025-01-03T00:00:00Z",
  },
  {
    id: "prod-foot-massage-roller-spiked",
    name: "Foot Massage Roller (Spiked)",
    slug: "foot-massage-roller-spiked",
    description:
      "Relax tired feet instantly with acupressure spikes that stimulate pressure points. Ideal for heel pain, plantar fasciitis relief, and improving blood circulation after long days.",
    price: 269,
    original_price: 498,
    discount_percentage: 46,
    category: "wellness",
    images: [],
    stock: 35,
    features: [
      "Spiked acupressure surface targets key foot pressure points",
      "Provides deep tissue massage for plantar fasciitis relief",
      "Improves blood circulation and reduces foot fatigue",
      "Durable ABS construction with non-slip texture",
      "Lightweight and portable — use at home or office",
    ],
    specifications: {
      Material: "ABS plastic with acupressure spikes",
      Dimensions: "25 cm × 8 cm",
      Weight: "250 g",
      "Max Load": "120 kg",
      Use: "Home, office, gym, travel",
    },
    is_active: true,
    created_at: "2025-01-04T00:00:00Z",
    updated_at: "2025-01-04T00:00:00Z",
  },
  {
    id: "prod-kitchen-sink-drain-hair-catcher",
    name: "Kitchen Sink Drain Hair Catcher",
    slug: "kitchen-sink-drain-hair-catcher",
    description:
      "Stop clogged drains with this adhesive mesh roll. Simply stick it over your drain — it catches hair, food debris, and gunk while letting water flow through freely. Each application lasts up to 6 weeks.",
    price: 189,
    original_price: 291,
    discount_percentage: 35,
    category: "kitchen",
    images: [],
    stock: 60,
    features: [
      "Adhesive mesh design — no tools, no installation needed",
      "Catches hair, food scraps, and debris before they clog pipes",
      "Cuttable to fit any drain size (sink, shower, tub)",
      "Lasts up to 6 weeks per application",
      "Transparent — nearly invisible when applied",
    ],
    specifications: {
      Material: "Adhesive mesh film",
      "Roll Size": "300 cm × 10 cm (cut to size)",
      "Per Application": "Lasts 4–6 weeks",
      "Suitable For": "Kitchen sinks, bathroom sinks, showers, tubs",
      "Pack Includes": "1 roll",
    },
    is_active: true,
    created_at: "2025-01-05T00:00:00Z",
    updated_at: "2025-01-05T00:00:00Z",
  },
  {
    id: "prod-magnetic-usb-cable-3-in-1",
    name: "Magnetic USB Cable 3-in-1",
    slug: "magnetic-usb-cable-3-in-1",
    description:
      "Charge your smartwatch, phone, and earbuds with one magnetic cable. Features 3 interchangeable tips (Apple Watch, Micro USB, USB-C) and fast charging support. 1 meter length.",
    price: 145,
    original_price: 250,
    discount_percentage: 42,
    category: "accessories",
    images: [],
    stock: 55,
    features: [
      "3 interchangeable magnetic tips (Apple Watch, Micro USB, USB-C)",
      "Magnetic auto-attach — aligns perfectly every time",
      "Fast charging supported (2A output)",
      "Durable braided nylon cable resists tangling",
      "LED indicator shows charging status",
    ],
    specifications: {
      Length: "1 meter",
      "Cable Material": "Braided nylon",
      "Input Type": "USB-A",
      "Output Tips": "Apple Watch / Micro USB / USB-C",
      "Max Output": "2A (fast charging)",
    },
    is_active: true,
    created_at: "2025-01-06T00:00:00Z",
    updated_at: "2025-01-06T00:00:00Z",
  },
  {
    id: "prod-menstrual-heating-pad-usb",
    name: "Menstrual Heating Pad (USB)",
    slug: "menstrual-heating-pad-usb",
    description:
      "Ease period pain naturally with this USB heating and massage pad. Features 3 heat levels and 3 vibration modes, cordless rechargeable battery, and a soft flexible design that stays in place.",
    price: 399,
    original_price: 767,
    discount_percentage: 48,
    category: "wellness",
    images: [],
    stock: 30,
    features: [
      "3 adjustable heat levels (35°C–65°C) for targeted relief",
      "3 vibration massage modes to soothe cramps",
      "Cordless and rechargeable — no wires while wearing",
      "Soft, flexible fabric hugs your body comfortably",
      "USB-C charging with 6+ hours of heat on low setting",
    ],
    specifications: {
      Material: "Soft polyester + carbon fiber heating element",
      "Heat Levels": "3 (35°C / 45°C / 65°C)",
      "Massage Modes": "3 vibration patterns",
      Battery: "2000 mAh (USB-C rechargeable)",
      "Battery Life": "6+ hours on low",
    },
    is_active: true,
    created_at: "2025-01-07T00:00:00Z",
    updated_at: "2025-01-07T00:00:00Z",
  },
  {
    id: "prod-posture-corrector-belt",
    name: "Posture Corrector Belt",
    slug: "posture-corrector-belt",
    description:
      "Fix your posture naturally with this breathable back support belt. Adjustable straps gently pull shoulders back, align your spine, and relieve back pain from poor posture. Comfortable for all-day wear.",
    price: 279,
    original_price: 507,
    discount_percentage: 45,
    category: "wellness",
    images: [],
    stock: 45,
    features: [
      "Dual-strap design gently pulls shoulders into proper alignment",
      "Breathable neoprene material — won't overheat during long wear",
      "Adjustable fit for men and women (chest 30–50 inches)",
      "Helps relieve upper back, shoulder, and neck pain",
      "Discreet — fits under clothing without bulging",
    ],
    specifications: {
      Material: "Breathable neoprene + elastic straps",
      "Chest Size": "30–50 inches (adjustable)",
      Weight: "150 g",
      Use: "Office work, driving, gaming, daily wear",
      Care: "Hand wash, air dry",
    },
    is_active: true,
    created_at: "2025-01-08T00:00:00Z",
    updated_at: "2025-01-08T00:00:00Z",
  },
  {
    id: "prod-silicone-oil-splatter-guard",
    name: "Silicone Oil Splatter Guard",
    slug: "silicone-oil-splatter-guard",
    description:
      "Stop oil splatters while frying! This flexible silicone mesh guard fits all pans and kadais. Food-grade silicone with fine mesh that lets steam escape while blocking oil splatters. Dishwasher safe.",
    price: 179,
    original_price: 298,
    discount_percentage: 40,
    category: "kitchen",
    images: [],
    stock: 50,
    features: [
      "Fine silicone mesh blocks oil splatters while letting steam escape",
      "Flexible design fits round pans & kadais (16–30 cm diameter)",
      "Food-grade silicone — BPA-free, non-toxic, heat resistant to 230°C",
      "Dishwasher safe for easy cleaning",
      "Built-in weight ring keeps it stable on the pan",
    ],
    specifications: {
      Material: "Food-grade silicone (BPA-free)",
      "Pan Size": "Fits 16–30 cm diameter pans & kadais",
      "Heat Resistance": "Up to 230°C",
      Cleaning: "Dishwasher safe or hand wash",
      Colour: "Red / Grey",
    },
    is_active: true,
    created_at: "2025-01-09T00:00:00Z",
    updated_at: "2025-01-09T00:00:00Z",
  },
  {
    id: "prod-waterproof-phone-pouch",
    name: "Waterproof Phone Pouch (Pack of 2)",
    slug: "waterproof-phone-pouch",
    description:
      "Keep your phone dry underwater, at the beach, or in the rain. This pack of 2 pouches fits all phones up to 7 inches, with a secure triple-lock seal and detachable lanyard for hands-free carrying.",
    price: 129,
    original_price: 287,
    discount_percentage: 55,
    category: "accessories",
    images: [],
    stock: 70,
    features: [
      "Triple-lock waterproof seal — IPX8 certified, submersible to 30m",
      "Fits all phones up to 7 inches (even with cases)",
      "Pack of 2 — share with a friend or keep a spare",
      "Detachable lanyard for hands-free wearing",
      "Touchscreen compatible — use your phone underwater",
    ],
    specifications: {
      Material: "Clear TPU + PVC",
      "Max Phone Size": "Up to 7 inches",
      "Waterproof Rating": "IPX8 (submersible to 30m)",
      "Pack Includes": "2 pouches + 2 lanyards",
      Use: "Swimming, beach, rain, hiking, travel",
    },
    is_active: true,
    created_at: "2025-01-10T00:00:00Z",
    updated_at: "2025-01-10T00:00:00Z",
  },
  {
    id: "prod-waterproof-shoe-covers",
    name: "Waterproof Shoe Covers",
    slug: "waterproof-shoe-covers",
    description:
      "Keep your shoes dry in rain and mud. These reusable waterproof shoe covers feature anti-slip rubber soles, elastic cuffs, and a lightweight design that folds into your bag. One size fits most adults.",
    price: 99,
    original_price: 198,
    discount_percentage: 50,
    category: "accessories",
    images: [],
    stock: 65,
    features: [
      "Waterproof outer layer keeps shoes completely dry",
      "Anti-slip rubber sole for safe walking on wet surfaces",
      "Elastic ankle cuff with drawstring — secure, no slipping",
      "Folds compactly into included carry pouch",
      "Reusable — rinse clean and air dry after each use",
    ],
    specifications: {
      Material: "Waterproof polyester + rubber sole",
      Size: "One size fits most adults (EU 36–46 / UK 3–11)",
      Weight: "120 g per pair",
      "Pack Includes": "1 pair + carry pouch",
      Use: "Rain, hiking, camping, travel, festivals",
    },
    is_active: true,
    created_at: "2025-01-11T00:00:00Z",
    updated_at: "2025-01-11T00:00:00Z",
  },
  {
    id: "prod-samsung-galaxy-s23-ultra",
    name: "Samsung Galaxy S23 Ultra",
    slug: "samsung-galaxy-s23-ultra",
    description:
      "Samsung Galaxy S23 Ultra — 200MP camera, S Pen, Snapdragon 8 Gen 2 for Galaxy, 12GB RAM, 512GB Storage, 5000mAh battery, Dynamic AMOLED 2X 120Hz display. International Version with dual SIM support. Graphite colour.",
    price: 24990,
    original_price: 124999,
    discount_percentage: 80,
    category: "phones",
    images: [],
    stock: 15,
    features: [
      "200MP Quad Camera with Space Zoom — capture stunning details even from afar",
      "S Pen included — take notes, sketch, and control your phone with precision",
      "Snapdragon 8 Gen 2 for Galaxy — fastest processor on any Android phone",
      "12GB RAM + 512GB Storage — massive space for apps, photos, and videos",
      "5000mAh battery with 45W fast charging — all-day power that lasts",
      'Dynamic AMOLED 2X, 120Hz display — 6.8" immersive edge screen',
    ],
    specifications: {
      Display: '6.8" Dynamic AMOLED 2X, 120Hz, 1440x3088',
      Processor: "Snapdragon 8 Gen 2 for Galaxy (4nm)",
      RAM: "12GB",
      Storage: "512GB (non-expandable)",
      "Rear Camera":
        "200MP wide + 10MP periscope telephoto + 10MP telephoto + 12MP ultrawide",
      "Front Camera": "12MP",
      Battery: "5000mAh, 45W fast charging, 15W wireless",
      OS: "Android 13, One UI 5.1 (upgradable to One UI 8.5)",
      SIM: "Dual Nano-SIM (International Version)",
      "5G Bands": "NSA/SA, Dual 5G support",
      Weight: "234g",
      Dimensions: "163.4 x 78.1 x 8.9 mm",
      "Water Resistance": "IP68 (1.5m for 30 min)",
      "S Pen": "Included, IP68 rated, Bluetooth Low Energy",
      Sensors:
        "Accelerometer, Barometer, Fingerprint (ultrasonic), Gyro, Geomagnetic, Hall, Light, Proximity",
      Colour: "Graphite",
    },
    is_active: true,
    created_at: "2025-12-01T00:00:00Z",
    updated_at: "2025-12-01T00:00:00Z",
  },
  {
    ...IPHONE_PRODUCT,
    id: "prod-apple-iphone-15-pro-max-512gb",
    name: "Apple iPhone 15 Pro Max 512GB",
    slug: "iphone-15-pro-max-512gb",
    category: "phones",
  },
  {
    id: "prod-messi-argentina-2026-jersey",
    name: "Messi Argentina 2026 Men's Local Jersey",
    slug: "messi-argentina-2026-jersey",
    description:
      "Dress like a champion with Messi's exact replica jersey for Argentina. Enjoy the comfort and flexibility of high-quality materials. Wear the pride of the Argentine national team with the Home Argentina 26 T-Shirt, Replica of the Messi Jersey — an ADIDAS original replica with premium detailing.",
    price: 499,
    original_price: 999,
    discount_percentage: 50,
    category: "worldcup-2026",
    images: [],
    stock: 100,
    features: [
      "High-quality replica of Messi's Argentina national team jersey — authentic ADIDAS design and detailing",
      "Breathable, lightweight fabric (222 g) for maximum comfort during matches and everyday wear",
      "Regular fit with short sleeves — suitable for all seasons and casual styling",
      "Striped pattern with authentic Argentina team colours and Messi's number 10",
      "Available in multiple sizes (S, M, L, XL, XXL) — find your perfect fit",
    ],
    specifications: {
      Brand: "ADIDAS (Original Replica)",
      "Fit Type": "Regular Fit",
      "Sleeve Type": "Short Sleeve",
      Pattern: "Striped",
      Seasons: "All",
      Material: "High-quality breathable fabric",
      Weight: "222 Grams",
      "Model Name": "Made in India-AR-10-2026",
      "Style Number": "KA8117-205",
      Manufacturer: "Made in India",
      "Age Range": "Adult",
      "Number of Items": "1",
    },
    is_active: true,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
];
